# file: .eslintrc.yml
# version: 1.0.0
# guid: 33333333-3333-4333-8333-333333333333

env:
    browser: true
    es2021: true
    node: true
extends:
    - eslint:recommended
parserOptions:
    ecmaVersion: latest
    sourceType: module
rules:
    no-console: off
    no-unused-vars:
        - warn
        - argsIgnorePattern: ^_
