# file: .golangci.yml
# version: 1.0.0
# guid: 66666666-6666-4666-8666-666666666666

run:
    timeout: 3m

linters:
    enable:
        - govet
        - staticcheck
        - gosimple
        - ineffassign
        - errcheck
        - typecheck
    disable:
        - depguard

issues:
    exclude-use-default: false
